apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: "{{ .Chart.Name }}-ingress"
  namespace: "{{ .Values.namespace }}"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: "{{ .Chart.Name }}"
              servicePort: 5000
            path: /healthcheck
          - backend:
              serviceName: "{{ .Chart.Name }}"
              servicePort: 5000
            path: /get_results
